export const theme = {
    colors: {
        primary: '#2D5A3D',
        secondary: '#F5F5DC',
        accent: '#E67E22',
        accentShade: '#D35400',
        error: '#E74C3C',
        warning: '#F39C12',
        success: '#27AE60',
        background: '#F8F9FA',
        surface: '#FFFFFF',
        text: '#000000',
        textSecondary: '#7F8C8D',
        border: '#000000',
        shadow: '#000000',
        lightGreen: '#52C41A',
        darkGreen: '#1F4E26',
        lightBlue: '#3498DB',
        darkBlue: '#2980B9',
        cream: '#FFF8E1',
        mint: '#A8E6CF',
    },
    breakpoints: {
        mobile: '768px',
        tablet: '1024px',
        desktop: '1366px',
    },
    spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
    },
    typography: {
        fontFamily: '"Space Grotesk", "Inter", sans-serif',
        fontWeight: {
            normal: 400,
            medium: 500,
            semibold: 600,
            bold: 700,
            black: 900,
        },
        fontSize: {
            xs: '12px',
            sm: '14px',
            md: '16px',
            lg: '18px',
            xl: '24px',
            xxl: '32px',
            huge: '48px',
        },
    },
};
