export const theme = {
    colors: {
        primary: '#000000',
        secondary: '#FFFFFF',
        accent: '#FF6B35',
        accentShade: '#E55A2B',
        error: '#FF1744',
        warning: '#FFD700',
        success: '#00C853',
        background: '#F5F5F5',
        surface: '#FFFFFF',
        text: '#000000',
        textSecondary: '#666666',
        border: '#000000',
        shadow: '#000000',
    },
    breakpoints: {
        mobile: '768px',
        tablet: '1024px',
        desktop: '1366px',
    },
    spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
    },
    typography: {
        fontFamily: '"Space Grotesk", "Inter", sans-serif',
        fontWeight: {
            normal: 400,
            medium: 500,
            semibold: 600,
            bold: 700,
            black: 900,
        },
        fontSize: {
            xs: '12px',
            sm: '14px',
            md: '16px',
            lg: '18px',
            xl: '24px',
            xxl: '32px',
            huge: '48px',
        },
    },
};
